config/routes.rb
Rails.application.routes.draw do
	root :to => 'books#index'
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.js
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end
 # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    #@book.destroy
    @book = Book.destroy(params[:id])

    respond_to do |format|
      format.js
      format.html { redirect_to @book, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }

    end
  end
  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
      @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update(book_params)
        format.js
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :year, :author, :description, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
 <tr id="<%= book.id %>">
    <td><%= book.title %></td>
    <td><%= book.year %></td>
    <td><%= book.author %></td>
    <td><%= book.description %></td>
    <td><%= book.price %></td>
    <!--<td><%= link_to "update", edit_book_path(book),remote: true %></td>-->
    <!--<td><%= link_to "(remove)", book, method: :delete,remote: true %></td>-->
    <td><%= link_to 'Destroy', book, method: :delete %></td>
    <td><%= link_to 'Edit', edit_book_path(book) %></td>

    <!--<td class='destroy'>Destroy</td>-->
    

</tr>     

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.date_select :year %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/create.js.erb
$('#new-book form').remove();
$('#new-book a').show();
$('table#books tbody').append("<%= j render @book %>");
$('#edit_book_<%= @book.id %>').submitOnCheck();

app/views/books/destroy.js.erb
$('#edit_book_<%= @book.id %>').remove();

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>
<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/edit.js.erb
$('#edit_book form').remove();
$('#edit_book a').show();
$('table#books tbody').append("<%= j render @book %>");
$('#edit_book a').hide().parent().append("<%= j render 'form',book: @book %>")  
//$('#edit_book_<%= @book.id %>').appendTo('#books'); 

//$('#edit_book_<%= @book.id %>').appendTo('#books'); 
//$('#new-book a').hide().parent().append("<%= j render 'form',book: @book %>")  

app/views/books/index.html.erb
<h1>Books</h1>

<table id="books">
  <thead>
    <tr>
      <th>Title</th>
      <th>Year</th>
      <th>Author</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @books%>
  </tbody>
</table>

<br>
<div id="new-book">

  <%= link_to 'New Book', new_book_path,remote: true %>

</div>

app/views/books/new.html.erb
<!--<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>
-->

app/views/books/new.js.erb
$('#new-book a').hide().parent().append("<%= j render 'form',book: @book %>")  

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Year:</strong>
  <%= @book.year %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/books/update.js.erb
$('#edit_book_<%= @book.id %>').appendTo('#books'); 
//$('#new-book a').hide().parent().append("<%= j render 'form',book: @book %>")  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Labsis3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>